package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "AVATAR".
 */
public class Avatar {

    private Long id;
    private String original;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Avatar() {
    }

    public Avatar(Long id) {
        this.id = id;
    }

    public Avatar(Long id, String original) {
        this.id = id;
        this.original = original;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getOriginal() {
        return original;
    }

    public void setOriginal(String original) {
        this.original = original;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
