package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Session;
import greendao.Category;
import greendao.User;
import greendao.Avatar;
import greendao.Post;
import greendao.Thumbnail;
import greendao.Screenshot;
import greendao.Comment;
import greendao.Vote;

import greendao.SessionDao;
import greendao.CategoryDao;
import greendao.UserDao;
import greendao.AvatarDao;
import greendao.PostDao;
import greendao.ThumbnailDao;
import greendao.ScreenshotDao;
import greendao.CommentDao;
import greendao.VoteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sessionDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig avatarDaoConfig;
    private final DaoConfig postDaoConfig;
    private final DaoConfig thumbnailDaoConfig;
    private final DaoConfig screenshotDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig voteDaoConfig;

    private final SessionDao sessionDao;
    private final CategoryDao categoryDao;
    private final UserDao userDao;
    private final AvatarDao avatarDao;
    private final PostDao postDao;
    private final ThumbnailDao thumbnailDao;
    private final ScreenshotDao screenshotDao;
    private final CommentDao commentDao;
    private final VoteDao voteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        avatarDaoConfig = daoConfigMap.get(AvatarDao.class).clone();
        avatarDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        thumbnailDaoConfig = daoConfigMap.get(ThumbnailDao.class).clone();
        thumbnailDaoConfig.initIdentityScope(type);

        screenshotDaoConfig = daoConfigMap.get(ScreenshotDao.class).clone();
        screenshotDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        voteDaoConfig = daoConfigMap.get(VoteDao.class).clone();
        voteDaoConfig.initIdentityScope(type);

        sessionDao = new SessionDao(sessionDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        avatarDao = new AvatarDao(avatarDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);
        thumbnailDao = new ThumbnailDao(thumbnailDaoConfig, this);
        screenshotDao = new ScreenshotDao(screenshotDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        voteDao = new VoteDao(voteDaoConfig, this);

        registerDao(Session.class, sessionDao);
        registerDao(Category.class, categoryDao);
        registerDao(User.class, userDao);
        registerDao(Avatar.class, avatarDao);
        registerDao(Post.class, postDao);
        registerDao(Thumbnail.class, thumbnailDao);
        registerDao(Screenshot.class, screenshotDao);
        registerDao(Comment.class, commentDao);
        registerDao(Vote.class, voteDao);
    }
    
    public void clear() {
        sessionDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        avatarDaoConfig.getIdentityScope().clear();
        postDaoConfig.getIdentityScope().clear();
        thumbnailDaoConfig.getIdentityScope().clear();
        screenshotDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        voteDaoConfig.getIdentityScope().clear();
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public AvatarDao getAvatarDao() {
        return avatarDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

    public ThumbnailDao getThumbnailDao() {
        return thumbnailDao;
    }

    public ScreenshotDao getScreenshotDao() {
        return screenshotDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public VoteDao getVoteDao() {
        return voteDao;
    }

}
