package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Session;
import greendao.Category;
import greendao.User;
import greendao.Post;

import greendao.SessionDao;
import greendao.CategoryDao;
import greendao.UserDao;
import greendao.PostDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig sessionDaoConfig;
    private final DaoConfig categoryDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig postDaoConfig;

    private final SessionDao sessionDao;
    private final CategoryDao categoryDao;
    private final UserDao userDao;
    private final PostDao postDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        postDaoConfig = daoConfigMap.get(PostDao.class).clone();
        postDaoConfig.initIdentityScope(type);

        sessionDao = new SessionDao(sessionDaoConfig, this);
        categoryDao = new CategoryDao(categoryDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        postDao = new PostDao(postDaoConfig, this);

        registerDao(Session.class, sessionDao);
        registerDao(Category.class, categoryDao);
        registerDao(User.class, userDao);
        registerDao(Post.class, postDao);
    }
    
    public void clear() {
        sessionDaoConfig.getIdentityScope().clear();
        categoryDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        postDaoConfig.getIdentityScope().clear();
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PostDao getPostDao() {
        return postDao;
    }

}
