package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "SCREENSHOT".
 */
public class Screenshot {

    // KEEP FIELDS - put your custom fields here

    private Long id;
    @SerializedName("300px")
    private String big;
    @SerializedName("850px")
    private String small;
    // KEEP FIELDS END

    public Screenshot() {
    }

    public Screenshot(Long id) {
        this.id = id;
    }

    public Screenshot(Long id, String big, String small) {
        this.id = id;
        this.big = big;
        this.small = small;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBig() {
        return big;
    }

    public void setBig(String big) {
        this.big = big;
    }

    public String getSmall() {
        return small;
    }

    public void setSmall(String small) {
        this.small = small;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
