package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "SESSION".
 */
public class Session {

    // KEEP FIELDS - put your custom fields here

    private static final String TOKEN_PREFIX = "Bearer ";

    private Long id;
    @SerializedName("access_token")
    private String accessToken;
    @SerializedName("expires_in")
    private Long expiresIn;
    // KEEP FIELDS END

    public Session() {
    }

    public Session(Long id) {
        this.id = id;
    }

    public Session(Long id, String accessToken, Long expiresIn) {
        this.id = id;
        this.accessToken = accessToken;
        this.expiresIn = expiresIn;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public Long getExpiresIn() {
        return expiresIn;
    }

    public void setExpiresIn(Long expiresIn) {
        this.expiresIn = expiresIn;
    }

    // KEEP METHODS - put your custom methods here

    public String getToken() {
        StringBuilder stringBuilder = new StringBuilder();
        return stringBuilder.append(TOKEN_PREFIX).append(accessToken).toString();
    }
    // KEEP METHODS END

}
