package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Session;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SESSION".
*/
public class SessionDao extends AbstractDao<Session, Long> {

    public static final String TABLENAME = "SESSION";

    /**
     * Properties of entity Session.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AccessToken = new Property(1, String.class, "accessToken", false, "ACCESS_TOKEN");
        public final static Property ExpiresIn = new Property(2, Long.class, "expiresIn", false, "EXPIRES_IN");
        public final static Property LastPostId = new Property(3, Long.class, "lastPostId", false, "LAST_POST_ID");
        public final static Property LastPostDay = new Property(4, String.class, "lastPostDay", false, "LAST_POST_DAY");
        public final static Property LastCommentId = new Property(5, Long.class, "lastCommentId", false, "LAST_COMMENT_ID");
        public final static Property LastVoteId = new Property(6, Long.class, "lastVoteId", false, "LAST_VOTE_ID");
    };


    public SessionDao(DaoConfig config) {
        super(config);
    }
    
    public SessionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SESSION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ACCESS_TOKEN\" TEXT," + // 1: accessToken
                "\"EXPIRES_IN\" INTEGER," + // 2: expiresIn
                "\"LAST_POST_ID\" INTEGER," + // 3: lastPostId
                "\"LAST_POST_DAY\" TEXT," + // 4: lastPostDay
                "\"LAST_COMMENT_ID\" INTEGER," + // 5: lastCommentId
                "\"LAST_VOTE_ID\" INTEGER);"); // 6: lastVoteId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SESSION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Session entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String accessToken = entity.getAccessToken();
        if (accessToken != null) {
            stmt.bindString(2, accessToken);
        }
 
        Long expiresIn = entity.getExpiresIn();
        if (expiresIn != null) {
            stmt.bindLong(3, expiresIn);
        }
 
        Long lastPostId = entity.getLastPostId();
        if (lastPostId != null) {
            stmt.bindLong(4, lastPostId);
        }
 
        String lastPostDay = entity.getLastPostDay();
        if (lastPostDay != null) {
            stmt.bindString(5, lastPostDay);
        }
 
        Long lastCommentId = entity.getLastCommentId();
        if (lastCommentId != null) {
            stmt.bindLong(6, lastCommentId);
        }
 
        Long lastVoteId = entity.getLastVoteId();
        if (lastVoteId != null) {
            stmt.bindLong(7, lastVoteId);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Session readEntity(Cursor cursor, int offset) {
        Session entity = new Session( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // accessToken
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // expiresIn
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // lastPostId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // lastPostDay
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // lastCommentId
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6) // lastVoteId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Session entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccessToken(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setExpiresIn(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setLastPostId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setLastPostDay(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLastCommentId(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setLastVoteId(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Session entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Session entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
