package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import com.google.gson.annotations.SerializedName;
// KEEP INCLUDES END
/**
 * Entity mapped to table "SESSION".
 */
public class Session {

    // KEEP FIELDS - put your custom fields here

    private static final String TOKEN_PREFIX = "Bearer ";

    private Long id;
    @SerializedName("access_token")
    private String accessToken;
    @SerializedName("expires_in")
    private Long expiresIn;
    private Long daysAgo;
    private java.util.Date lastPostDate;
    private Long lastCommentId;
    private Long lastVoteId;
    // KEEP FIELDS END

    public Session() {
    }

    public Session(Long id) {
        this.id = id;
    }

    public Session(Long id, String accessToken, Long expiresIn, java.util.Date lastPostDate, Long lastCommentId, Long lastVoteId) {
        this.id = id;
        this.accessToken = accessToken;
        this.expiresIn = expiresIn;
        this.lastPostDate = lastPostDate;
        this.lastCommentId = lastCommentId;
        this.lastVoteId = lastVoteId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public Long getExpiresIn() {
        return expiresIn;
    }

    public void setExpiresIn(Long expiresIn) {
        this.expiresIn = expiresIn;
    }

    public java.util.Date getLastPostDate() {
        return lastPostDate;
    }

    public void setLastPostDate(java.util.Date lastPostDate) {
        this.lastPostDate = lastPostDate;
    }

    public Long getLastCommentId() {
        return lastCommentId;
    }

    public void setLastCommentId(Long lastCommentId) {
        this.lastCommentId = lastCommentId;
    }

    public Long getLastVoteId() {
        return lastVoteId;
    }

    public void setLastVoteId(Long lastVoteId) {
        this.lastVoteId = lastVoteId;
    }

    // KEEP METHODS - put your custom methods here

    public String getToken() {
        StringBuilder stringBuilder = new StringBuilder();
        return stringBuilder.append(TOKEN_PREFIX).append(accessToken).toString();
    }
    // KEEP METHODS END

}
